<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';

// Get JSON input
$json = file_get_contents('php://input');
$data = json_decode($json, true);

// If not JSON, try $_POST
if (!$data) {
    $data = $_POST;
}

// Escape function
function escape($str) {
    return htmlspecialchars(trim($str ?? ''), ENT_QUOTES, 'UTF-8');
}

$name = escape($data['name'] ?? '');
$classOrPosition = escape($data['classOrPosition'] ?? '');
$organization = escape($data['organization'] ?? '');
$to = escape($data['to'] ?? '');
$toOrganization = escape($data['toOrganization'] ?? '');
$date = escape($data['date'] ?? '');
$subject = escape($data['subject'] ?? '');
$respected = escape($data['respected'] ?? '');
$body = escape($data['body'] ?? '');
$closing = nl2br(escape($data['closing'] ?? ''));

// Start HTML
$html = "
    <div style='font-family: Arial, sans-serif; color: #333;'>
        <h1 style='text-align:center; color: #4F46E5;'>Application</h1>
        <hr style='border: 0; border-top: 1px solid #eee;'>
        
        <div style='text-align: right; margin-bottom: 30px;'>
            " . ($name ? "<p style='margin: 0; font-weight: bold;'>$name</p>" : "") . "
            " . ($classOrPosition ? "<p style='margin: 0;'>$classOrPosition</p>" : "") . "
            " . ($organization ? "<p style='margin: 0;'>$organization</p>" : "") . "
            " . ($date ? "<p style='margin: 0;'>$date</p>" : "") . "
        </div>

        <div style='margin-bottom: 20px;'>
            <p style='margin: 0; font-weight: bold;'>To,</p>
            " . ($to ? "<p style='margin: 0;'>$to</p>" : "") . "
            " . ($toOrganization ? "<p style='margin: 0;'>$toOrganization</p>" : "") . "
        </div>

        <div style='margin-bottom: 20px;'>
            <p><strong>Subject:</strong> $subject</p>
        </div>

        <div style='margin-bottom: 15px;'>
            <p>$respected</p>
        </div>

        <div style='margin-bottom: 30px; line-height: 1.6; text-align: justify;'>
            <p>" . nl2br($body) . "</p>
        </div>

        <div style='text-align: right; margin-top: 50px;'>
            <p style='white-space: pre-wrap;'>$closing</p>
        </div>
    </div>
";

// mPDF
$mpdf = new \Mpdf\Mpdf([
    'mode' => 'utf-8',
    'format' => 'A4',
    'margin_left' => 20,
    'margin_right' => 20,
    'margin_top' => 20,
    'margin_bottom' => 20
]);

$mpdf->SetHTMLFooter("
    <hr style='border: 0; border-top: 1px solid #eee;'>
    <div style='text-align: center; font-size: 10px; color: #999; padding-top: 10px;'>
        Generated by <a href='https://asmdocx.vercel.app'>asmDocx</a>
    </div>
");

$mpdf->WriteHTML($html);
$mpdf->Output('application.pdf', 'I');
