<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';

// Get JSON input
$json = file_get_contents('php://input');
$data = json_decode($json, true);

// If not JSON, try $_POST
if (!$data) {
    $data = $_POST;
}

// Escape function
function escape($str) {
    return htmlspecialchars(trim($str ?? ''), ENT_QUOTES, 'UTF-8');
}

$from = escape($data['from'] ?? 'Unknown');
$to = escape($data['to'] ?? 'Unknown');
$subject = escape($data['subject'] ?? 'No Subject');
$greeting = escape($data['greeting'] ?? 'Dear Sir/Madam,');
$summary = escape($data['summary'] ?? 'No Summary');
$closing = escape($data['closing'] ?? 'Yours faithfully');

// Start HTML
$html = "
    <div style='font-family: Arial, sans-serif; color: #333;'>
        <h1 style='text-align:center; color: #4F46E5;'>Email</h1>
        <hr style='border: 0; border-top: 1px solid #eee;'>
        
        <div style='margin-bottom: 30px;'>
            <p style='margin: 0 0 5px 0;'><strong>From:</strong> $from</p> <br>
            <p style='margin: 0 0 5px 0;'><strong>To:</strong> $to</p> <br>
            <p style='margin: 0;'><strong>Subject:</strong> $subject</p> <br>
        </div>

        <div style='margin-bottom: 15px;'>
            <p>$greeting</p>
        </div>

        <div style='margin-bottom: 30px; line-height: 1.6;'>
            <p>" . nl2br($summary) . "</p>
        </div>

        <div style='margin-top: 40px;'>
            <p style='white-space: pre-wrap;'>" . nl2br($closing) . "</p>
        </div>
    </div>
";

// mPDF
$mpdf = new \Mpdf\Mpdf([
    'mode' => 'utf-8',
    'format' => 'A4',
    'margin_left' => 20,
    'margin_right' => 20,
    'margin_top' => 20,
    'margin_bottom' => 20
]);

// Set footer
$mpdf->SetHTMLFooter("
    <hr style='border: 0; border-top: 1px solid #eee;'>
    <div style='text-align: center; font-size: 10px; color: #999; padding-top: 10px;'>
        Generated by <a href='https://asmdocx.vercel.app'>asmDocx</a>
    </div>
");

$mpdf->WriteHTML($html);
$mpdf->Output('email.pdf', 'I');
